name: stream
version: 1.0.0
description: > 
  Lightweight Dart web server supporting request routing, filtering,
  template engine, MVC design pattern, and file-based static resources.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream
dependencies:
  rikulo_commons: any
  logging: any
  args: any
  path: any
environment:
  sdk: ">=1.0.0"
