name: stream
version: 2.2.0
description: > 
  Lightweight Dart web server supporting request routing, filtering,
  template engine, MVC design pattern, and file-based static resources.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream
dependencies:
  rikulo_commons: '>=3.0.0 <4.0.0'
  logging: ">=0.11.0 <2.0.0"
  args: '>=0.13.0 <2.0.0'
  path: '>=1.3.0 <2.0.0'
  http: '>=0.11.0 <2.0.0'
  charcode: ">=1.1.0 <2.0.0"

executables:
  rspc:

environment:
  sdk: '>=2.0.0 <3.0.0'
