name: stream
version: 0.5.3+1
description: > 
  Stream is a Dart web server supporting request routing, filtering,
  template technology, file-based static resources and MVC design pattern.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
dependencies:
  rikulo_commons: any
  logging: any
  args: any
  meta: any
